title: ERP Warehouse Developer Guide
description: Internal documentation for the Warehouse module (Laravel 10)
url: "https://gamalsobhy585.github.io"
baseurl: "/documentation-of-warehouse"
color_scheme: dark


remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme


search_enabled: true
heading_anchors: true
logo: "{{ '/assets/images.png' | relative_url }}"

aux_links:
  "View on GitHub":
    - "https://github.com/Gamalsobhy585/documentation-of-warehouse"

# ---- Footer
footer_content: "© <script>document.write(new Date().getFullYear())</script> EEC. All rights reserved."

# ---- Navigation options
nav_external_links:
  - title: ERP Portal
    url: https://erp.example.com

# ---- Markdown / build
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
